[package]
name = "wasm-bindgen-benchmark"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]

[dependencies]
# wasm-bindgen = "0.2.43"
wasm-bindgen = { path = "../../../wasm-bindgen" }

[lib]
crate-type = ['cdylib']

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
